name: build-push
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '15 12 * * *'

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
    - uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1' # v7

    - uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
      with:
        dockerfile: Dockerfile
        verbose: true

    - name: check valid sh
      run: shellcheck **/*.sh

  # get the apk cache set before building the other images
  cache-seed:
    needs: [lint]
    strategy:
      matrix:
        php-version: ["8.3", "8.4", "8.5"]
      fail-fast: false
    uses: ./.github/workflows/build-image.yml
    with:
      php-version: ${{ matrix.php-version }}
      drupal-version: "11.4.x"
    permissions:
      contents: read
      packages: write

  # build the rest of the Drupal+php images
  build-push:
    needs: [cache-seed]
    strategy:
      matrix:
        php-version: ["8.3", "8.4", "8.5"]
        drupal-version: ["10.6.x", "11.3.x"]
      max-parallel: 3
      fail-fast: false
    uses: ./.github/workflows/build-image.yml
    with:
      php-version: ${{ matrix.php-version }}
      drupal-version: ${{ matrix.drupal-version }}
    permissions:
      contents: read
      packages: write
